version: '3.8'
services:
  app:
    build: .
    #volumes:
     #   - ./app.py/app/app.py
      #  - ./students.csv:/app/students.csv

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app