# _*_ mode: ruby _*_
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "jenkins-master" do |master|
        master.vm.box = "ubuntu/focal64"
        master.vm.provider "virtualbox" do |vb|
            vb.name = "jenkinsmaster"
            vb.memory = "2048"
            vb.cpus = "2"
        end

        master.vm.network "private_network", ip: "192.168.56.10"

         master.vm.provision "file", source: "./jenkins_key", destination: "/home/vagrant/.ssh/jenkins_key"

        master.vm.provision "shell", inline: <<-SHELL
            export DEBIAN_FRONTEND=noninteractive
            echo ">>> updating packages ..."
            sudo apt-get update -y

            echo ">>> install Java ..."
            sudo apt-get install -y openjdk-17-jdk

            echo ">>> install docker ..."
            sudo apt-get install -y docker.io
            sudo usermod -aG docker vagrant

            sudo chown vagrant:vagrant /home/vagrant/.ssh/jenkins_key
            sudo chmod 600 /home/vagrant/.ssh/jenkins_key

            echo ">>> install Jenkis ..."
            curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
            echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
            sudo apt-get update -y
            sudo apt-get install -y jenkins
            sudo systemctl start jenkins
        SHELL
    end

    config.vm.define "jenkins-worker" do |worker|
        worker.vm.box = "ubuntu/focal64"

        worker.vm.provider "virtualbox" do |vb|
            vb.name = "JenkinsWorker"
            vb.memory = "1024"
            vb.cpus = "1"
        end

        worker.vm.network "private_network", ip: "192.168.56.11"

        worker.vm.provision "shell", inline: <<-SHELL
            export DEBIAN_FRONTEND=noninteractive
            echo ">>> updating packages ..."
            sudo apt-get update -y

            echo ">>> install Java ..."
            sudo apt-get install -y openjdk-17-jdk

            echo ">>> install docker ..."
            sudo apt-get install -y docker.io
            sudo usermod -aG docker vagrant

            mkdir -p /home/vagrant/.ssh
            touch /home/vagrant/.ssh/authorized_keys
            chmod 700 /home/vagrant/.ssh
            chmod 600 /home/vagrant/.ssh/authorized_keys
            chown -R vagrant:vagrant /home/vagrant/.ssh
            cat /vagrant/jenkins_key.pub >> /home/vagrant/.ssh/authorized_keys
        SHELL
    end

end